export const ORDER_STATUS = Object.freeze({
  PLACED: "PLACED",
  CONFIRMED: "CONFIRMED",
  PACKED: "PACKED",
  ASSIGNED_TO_DELIVERY: "ASSIGNED_TO_DELIVERY",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  RETURNED: "RETURNED",
});

export const ORDER_STATUS_FLOW = Object.freeze([
  ORDER_STATUS.PLACED,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PACKED,
  ORDER_STATUS.ASSIGNED_TO_DELIVERY,
  ORDER_STATUS.OUT_FOR_DELIVERY,
  ORDER_STATUS.DELIVERED,
]);

export const PAYMENT_METHOD = Object.freeze({
  COD: "COD",
  ONLINE: "ONLINE",
  WALLET: "WALLET",
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
});

export const TICKET_STATUS = Object.freeze({
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  ESCALATED: "ESCALATED",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
});

export const DELIVERY_PARTNER_STATUS = Object.freeze({
  OFFLINE: "OFFLINE",
  ONLINE: "ONLINE",
  ON_DELIVERY: "ON_DELIVERY",
});

export const SELLER_STATUS = Object.freeze({
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  SUSPENDED: "SUSPENDED",
  REJECTED: "REJECTED",
});

export const OTP_CHANNEL = Object.freeze({
  EMAIL: "EMAIL",
  MOBILE: "MOBILE",
});
